// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuTauh48o5AlzcvDrN6Z3cz2TOHXE4QVQ',
    appId: '1:516790082055:web:4347a496d991309ccae8a2',
    messagingSenderId: '516790082055',
    projectId: 'notes-a522f',
    authDomain: 'notes-a522f.firebaseapp.com',
    databaseURL: 'https://notes-a522f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'notes-a522f.appspot.com',
    measurementId: 'G-TEHC3SZZX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJBSqUlfibgMGqOGE1iYRD59_SqjkahDo',
    appId: '1:516790082055:android:77ef5b5d6ab088bacae8a2',
    messagingSenderId: '516790082055',
    projectId: 'notes-a522f',
    databaseURL: 'https://notes-a522f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'notes-a522f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7EAMJdvnNAudlPiKbzyi892eQXR-TQT4',
    appId: '1:516790082055:ios:215d2bccebc08a92cae8a2',
    messagingSenderId: '516790082055',
    projectId: 'notes-a522f',
    databaseURL: 'https://notes-a522f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'notes-a522f.appspot.com',
    iosClientId: '516790082055-p2sq8cmdeahcfpkl9tpadsbnvoqmdfqr.apps.googleusercontent.com',
    iosBundleId: 'com.doofer.app',
  );
}
